n1 = int(input('Um valor:'))
n2 = int(input('Outro valor:'))
print ('A soma vale {}'.format(n1+n2))
print ('A subtração vale {}'.format(n1-n2))
print('O produto vale {}'.format (n1*n2))
print ('Divisão inteira {}'.format(n1//n2))
print ('Potência: {}'.format(n1**n2))
print ('a divisão {}'.format(n1/n2))